# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example_iOS_5' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'CHIPageControl', :path => '../'

  #pod 'CHIPageControl/Puya', :path => '../'

end
